# Generated by Django 3.2.1 on 2021-05-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210515_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('review_text', models.TextField(verbose_name='Текст отзыва')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AlterModelOptions(
            name='cosmetologyservices',
            options={},
        ),
        migrations.AlterModelOptions(
            name='manicurepedicure',
            options={},
        ),
        migrations.AlterModelOptions(
            name='servicesforchildren',
            options={},
        ),
        migrations.AlterModelOptions(
            name='servicesformen',
            options={},
        ),
        migrations.AlterModelOptions(
            name='servicesforwomen',
            options={},
        ),
    ]
